package cn.gqlife.utils;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 
 * @author Administrator
 * 
 */
public class FunHelper {
	
	
	public static String getAreaCity(String cityId) {
		String cityName = "中山市";
		Map<String, String> map = new HashMap<String, String>();
		map.put("01", "东区");
		map.put("02", "石岐区");
		map.put("03", "西区");
		map.put("04", "南区");
		map.put("05", "火炬开发区");
		map.put("06", "五桂山区");
		map.put("07", "港口镇");
		map.put("08", "沙溪镇");
		map.put("09", "小榄镇");
		map.put("10", "古镇");
		map.put("11", "东升镇");
		map.put("12", "南头镇");
		map.put("13", "阜沙镇");
		map.put("14", "黄埔镇");
		map.put("15", "三角镇");
		map.put("16", "民众镇");
		map.put("17", "东凤镇");
		map.put("18", "横栏镇");
		map.put("19", "大涌镇");
		map.put("20", "三乡镇");
		map.put("21", "南朗镇");
		map.put("22", "坦洲镇");
		map.put("23", "神湾镇");
		map.put("24", "板芙镇");
		if (cityId != null && !cityId.equals("00") && cityId.length() == 2) {
			cityName = map.get(cityId);
		}
		return cityName;
	}

	public static String getBusinessArea(String cityId) {
		String cityName = "";
		Map<String, String> map = new HashMap<String, String>();
		map.put("0100", "东区");
		map.put("0101", "假日广场");
		map.put("0102", "库充一带");
		map.put("0103", "中山海关");
		map.put("0104", "竹苑周边");
		map.put("0105", "远洋城");
		map.put("0106", "京华利和");
		map.put("0107", "白沙湾");
		map.put("0108", "东裕路");
		map.put("0109", "利和广场");
		map.put("0200", "石岐区");
		map.put("0201", "大信新都汇");
		map.put("0202", "逢源商业街");
		map.put("0203", "孙文步行街");
		map.put("0204", "峰华28广场");
		map.put("0205", "泰安路");
		map.put("0206", "兴中广场");
		map.put("0300", "西区");
		map.put("0301", "歧江公园");
		map.put("0302", "富华商圈");
		map.put("0303", "黄金广场");
		map.put("0304", "翠景商业街");
		map.put("0400", "南区");
		map.put("0401", "万科一带");
		map.put("0402", "悦来南路");
		map.put("0403", "南下新码头");
		map.put("0500", "火炬开发区");
		map.put("0501", "张家边");
		map.put("0502", "中山港");
		map.put("0600", "五桂山区");
		map.put("0601", "长命水广药");
		map.put("0700", "港口镇");
		map.put("0701", "美景花园");
		map.put("0702", "港口市场");
		map.put("0800", "沙溪镇");
		map.put("0801", "星宝");
		map.put("0900", "小榄镇");
		map.put("0901", "大信顺昌");
		map.put("0902", "永宁");
		map.put("0903", "小榄");
		map.put("1000", "古镇");
		map.put("1001", "古镇");
		map.put("1002", "国贸");
		map.put("1100", "东升镇");
		map.put("1200", "南头镇");
		map.put("1300", "阜沙镇");
		map.put("1400", "黄埔镇");
		map.put("1500", "三角镇");
		map.put("1600", "民众镇");
		map.put("1700", "东凤镇");
		map.put("1701", "名扬世纪广场");
		map.put("1800", "横栏镇");
		map.put("1900", "大涌镇");
		map.put("2000", "三乡镇");
		map.put("2001", "雅居乐酒店");
		map.put("2002", "华丰片区");
		map.put("2003", "三乡市场");
		map.put("2004", "顺昌广场");
		map.put("2100", "南朗镇");
		map.put("2200", "坦洲镇");
		map.put("2300", "神湾镇");
		map.put("2400", "板芙镇");
		if (cityId != null && !cityId.equals("0000") && cityId.length() == 4) {
			cityName = map.get(cityId);
		}
		return cityName;
	}

	public static List<CityBean> getCityAreaList() {
		List<CityBean> list = new ArrayList<CityBean>();
		CityBean bean = new CityBean();
		bean.setCityId("01");
		bean.setCityName("东区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("02");
		bean.setCityName("石岐区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("03");
		bean.setCityName("西区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("04");
		bean.setCityName("南区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("05");
		bean.setCityName("火炬开发区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("06");
		bean.setCityName("五桂山区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("07");
		bean.setCityName("港口镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("08");
		bean.setCityName("沙溪镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("09");
		bean.setCityName("小榄镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("10");
		bean.setCityName("古镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("11");
		bean.setCityName("东升镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("12");
		bean.setCityName("南头镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("13");
		bean.setCityName("阜沙镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("14");
		bean.setCityName("黄埔镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("15");
		bean.setCityName("三角镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("16");
		bean.setCityName("民众镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("17");
		bean.setCityName("东凤镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("18");
		bean.setCityName("横栏镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("19");
		bean.setCityName("大涌镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("20");
		bean.setCityName("三乡镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("21");
		bean.setCityName("南朗镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("22");
		bean.setCityName("坦洲镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("23");
		bean.setCityName("神湾镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityId("24");
		bean.setCityName("板芙镇");
		list.add(bean);
		return list;
	}

	public static List<CityBean> getBusinessAreaList() {
		List<CityBean> list = new ArrayList<CityBean>();
		CityBean bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0100");
		bean.setCityName("东区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0101");
		bean.setCityName("假日广场");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0102");
		bean.setCityName("库充一带");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0103");
		bean.setCityName("中山海关");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0104");
		bean.setCityName("竹苑周边");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0105");
		bean.setCityName("远洋城");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0106");
		bean.setCityName("京华利和");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0107");
		bean.setCityName("白沙湾");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0108");
		bean.setCityName("东裕路");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0109");
		bean.setCityName("利和广场");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0200");
		bean.setCityName("石岐区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0201");
		bean.setCityName("大信新都汇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0202");
		bean.setCityName("逢源商业街");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0203");
		bean.setCityName("孙文步行街");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0204");
		bean.setCityName("峰华28广场");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0205");
		bean.setCityName("泰安路");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0206");
		bean.setCityName("兴中广场");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("03");
		bean.setCityId("0300");
		bean.setCityName("西区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("03");
		bean.setCityId("0301");
		bean.setCityName("歧江公园");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("03");
		bean.setCityId("0302");
		bean.setCityName("富华商圈");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("03");
		bean.setCityId("0303");
		bean.setCityName("黄金广场");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("03");
		bean.setCityId("0304");
		bean.setCityName("翠景商业街");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("04");
		bean.setCityId("0400");
		bean.setCityName("南区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("04");
		bean.setCityId("0401");
		bean.setCityName("万科一带");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("04");
		bean.setCityId("0402");
		bean.setCityName("悦来南路");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("04");
		bean.setCityId("0403");
		bean.setCityName("南下新码头");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("05");
		bean.setCityId("0500");
		bean.setCityName("火炬开发区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("05");
		bean.setCityId("0501");
		bean.setCityName("张家边");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("05");
		bean.setCityId("0502");
		bean.setCityName("中山港");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("06");
		bean.setCityId("0600");
		bean.setCityName("五桂山区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("06");
		bean.setCityId("0601");
		bean.setCityName("长命水广药");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("07");
		bean.setCityId("0700");
		bean.setCityName("港口镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("07");
		bean.setCityId("0701");
		bean.setCityName("美景花园");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("07");
		bean.setCityId("0702");
		bean.setCityName("港口市场");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("08");
		bean.setCityId("0800");
		bean.setCityName("沙溪镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("08");
		bean.setCityId("0801");
		bean.setCityName("星宝");
		list.add(bean);
		/*
		 * bean=new CityBean();bean.setCityPid("09"); bean.setCityId("0900");
		 * bean.setCityName("小榄镇"); list.add(bean);
		 */
		bean = new CityBean();
		bean.setCityPid("09");
		bean.setCityId("0901");
		bean.setCityName("大信顺昌");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("09");
		bean.setCityId("0902");
		bean.setCityName("永宁");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("09");
		bean.setCityId("0903");
		bean.setCityName("小榄");
		list.add(bean);
		/*
		 * bean=new CityBean();bean.setCityPid("10"); bean.setCityId("1000");
		 * bean.setCityName("古镇"); list.add(bean);
		 */
		bean = new CityBean();
		bean.setCityPid("10");
		bean.setCityId("1001");
		bean.setCityName("古镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("10");
		bean.setCityId("1002");
		bean.setCityName("国贸");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("11");
		bean.setCityId("1100");
		bean.setCityName("东升镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("12");
		bean.setCityId("1200");
		bean.setCityName("南头镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("13");
		bean.setCityId("1300");
		bean.setCityName("阜沙镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("14");
		bean.setCityId("1400");
		bean.setCityName("黄埔镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("15");
		bean.setCityId("1500");
		bean.setCityName("三角镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("16");
		bean.setCityId("1600");
		bean.setCityName("民众镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("17");
		bean.setCityId("1700");
		bean.setCityName("东凤镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("17");
		bean.setCityId("1701");
		bean.setCityName("名扬世纪广场");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("18");
		bean.setCityId("1800");
		bean.setCityName("横栏镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("19");
		bean.setCityId("1900");
		bean.setCityName("大涌镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("20");
		bean.setCityId("2000");
		bean.setCityName("三乡镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("20");
		bean.setCityId("2001");
		bean.setCityName("雅居乐酒店");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("20");
		bean.setCityId("2002");
		bean.setCityName("华丰片区");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("20");
		bean.setCityId("2003");
		bean.setCityName("三乡市场");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("20");
		bean.setCityId("2004");
		bean.setCityName("顺昌广场");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("21");
		bean.setCityId("2100");
		bean.setCityName("南朗镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("22");
		bean.setCityId("2200");
		bean.setCityName("坦洲镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("23");
		bean.setCityId("2300");
		bean.setCityName("神湾镇");
		list.add(bean);
		bean = new CityBean();
		bean.setCityPid("24");
		bean.setCityId("2400");
		bean.setCityName("板芙镇");
		list.add(bean);
		return list;
	}

	public static String getCityAreaName(String cityId) {
		String ctiyname = "";
		if (cityId != null && !cityId.isEmpty() && cityId.length() == 2) {
			for (CityBean bean : getCityAreaList()) {
				if (bean != null && bean.getCityId().equals(cityId)) {
					ctiyname = bean.getCityName();
					break;
				}
			}
		}
		return ctiyname;
	}

	public static String getBusinessAreaName(String cityId) {
		String ctiyname = "";
		if (cityId != null && !cityId.isEmpty() && cityId.length() == 4) {
			for (CityBean bean : getBusinessAreaList()) {
				if (bean != null && bean.getCityId().equals(cityId)) {
					ctiyname = bean.getCityName();
					break;
				}
			}
		}
		return ctiyname;
	}

	public static AreaBean getCityAreaList(String cityId) {
		AreaBean tbean = new AreaBean();
		tbean.setAreaId(cityId);
		tbean.setAreaName(getCityAreaName(cityId));
		List<CityBean> list = new ArrayList<CityBean>();
		if (cityId != null && !cityId.isEmpty()) {
			for (CityBean bean : getBusinessAreaList()) {
				if (bean != null && bean.getCityId() != null
						&& bean.getCityId().length() == 4
						&& bean.getCityId().substring(0, 2).equals(cityId)
						&& bean.getCityPid().equals(cityId)) {
					list.add(bean);
				}
			}
		}
		tbean.setCityBeanList(list);
		return tbean;
	}

	public static List<AreaBean> getAreaList() {
		List<AreaBean> list = new ArrayList<AreaBean>();
		List<CityBean> tlist = new ArrayList<CityBean>();
		AreaBean abean = new AreaBean();
		abean.setAreaId("01");
		abean.setAreaName("东区");
		CityBean bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0101");
		bean.setCityName("假日广场");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0102");
		bean.setCityName("库充一带");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0103");
		bean.setCityName("中山海关");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0104");
		bean.setCityName("竹苑周边");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0105");
		bean.setCityName("远洋城");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0106");
		bean.setCityName("京华利和");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0107");
		bean.setCityName("白沙湾");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0108");
		bean.setCityName("东裕路");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("01");
		bean.setCityId("0109");
		bean.setCityName("利和广场");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("02");
		abean.setAreaName("石岐区");
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0201");
		bean.setCityName("大信新都汇");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0202");
		bean.setCityName("逢源商业街");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0203");
		bean.setCityName("孙文步行街");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0204");
		bean.setCityName("峰华28广场");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0205");
		bean.setCityName("泰安路");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("02");
		bean.setCityId("0206");
		bean.setCityName("兴中广场");
		list.add(abean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("0300");
		abean.setAreaName("西区");
		bean = new CityBean();
		bean.setCityPid("03");
		bean.setCityId("0301");
		bean.setCityName("歧江公园");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("03");
		bean.setCityId("0302");
		bean.setCityName("富华商圈");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("03");
		bean.setCityId("0303");
		bean.setCityName("黄金广场");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("03");
		bean.setCityId("0304");
		bean.setCityName("翠景商业街");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("04");
		abean.setAreaName("南区");

		bean = new CityBean();
		bean.setCityPid("04");
		bean.setCityId("0401");
		bean.setCityName("万科一带");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("04");
		bean.setCityId("0402");
		bean.setCityName("悦来南路");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("04");
		bean.setCityId("0403");
		bean.setCityName("南下新码头");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("05");
		abean.setAreaName("火炬开发区");
		bean = new CityBean();
		bean.setCityPid("05");
		bean.setCityId("0501");
		bean.setCityName("张家边");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("05");
		bean.setCityId("0502");
		bean.setCityName("中山港");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("06");
		abean.setAreaName("五桂山区");
		bean = new CityBean();
		bean.setCityPid("06");
		bean.setCityId("0601");
		bean.setCityName("长命水广药");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("07");
		abean.setAreaName("港口镇");

		bean = new CityBean();
		bean.setCityPid("07");
		bean.setCityId("0701");
		bean.setCityName("美景花园");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("07");
		bean.setCityId("0702");
		bean.setCityName("港口市场");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("08");
		abean.setAreaName("沙溪镇");

		bean = new CityBean();
		bean.setCityPid("08");
		bean.setCityId("0801");
		bean.setCityName("星宝");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("09");
		abean.setAreaName("小榄镇");

		bean = new CityBean();
		bean.setCityPid("09");
		bean.setCityId("0901");
		bean.setCityName("大信顺昌");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("09");
		bean.setCityId("0902");
		bean.setCityName("永宁");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("09");
		bean.setCityId("0903");
		bean.setCityName("小榄");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("10");
		abean.setAreaName("古镇");
		bean = new CityBean();
		bean.setCityPid("10");
		bean.setCityId("1001");
		bean.setCityName("古镇");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("10");
		bean.setCityId("1002");
		bean.setCityName("国贸");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("11");
		abean.setAreaName("东升镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("12");
		abean.setAreaName("南头镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("13");
		abean.setAreaName("阜沙镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("14");
		abean.setAreaName("黄埔镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("15");
		abean.setAreaName("三角镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("16");
		abean.setAreaName("民众镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("17");
		abean.setAreaName("东凤镇");
		bean = new CityBean();
		bean.setCityPid("17");
		bean.setCityId("1701");
		bean.setCityName("名扬世纪广场");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("18");
		abean.setAreaName("横栏镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("19");
		abean.setAreaName("大涌镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("20");
		abean.setAreaName("三乡镇");
		bean = new CityBean();
		bean.setCityPid("20");
		bean.setCityId("2001");
		bean.setCityName("雅居乐酒店");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("20");
		bean.setCityId("2002");
		bean.setCityName("华丰片区");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("20");
		bean.setCityId("2003");
		bean.setCityName("三乡市场");
		tlist.add(bean);
		bean = new CityBean();
		bean.setCityPid("20");
		bean.setCityId("2004");
		bean.setCityName("顺昌广场");
		tlist.add(bean);
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("21");
		abean.setAreaName("南朗镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("22");
		abean.setAreaName("坦洲镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("23");
		abean.setAreaName("神湾镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		abean = new AreaBean();
		tlist = new ArrayList<CityBean>();
		abean.setAreaId("24");
		abean.setAreaName("板芙镇");
		abean.setCityBeanList(tlist);
		list.add(abean);
		return list;
	}

}
